# Faça um programa que leia um numero inteiro qualquer e mostre na tela sua tabuada

numero = int(input('Digite um número para vê sua tabuada: '))
print('-'*11)
print('{} X {:2} = {}'.format(numero, 1, numero * 1))
print('{} X {:2} = {}'.format(numero, 2, numero * 2))
print('{} X {:2} = {}'.format(numero, 3, numero * 3))
print('{} X {:2} = {}'.format(numero, 4, numero * 4))
print('{} X {:2} = {}'.format(numero, 5, numero * 5))
print('{} X {:2} = {}'.format(numero, 6, numero * 6))
print('{} X {:2} = {}'.format(numero, 7, numero * 7))
print('{} X {:2} = {}'.format(numero, 8, numero * 8))
print('{} X {:2} = {}'.format(numero, 9, numero * 9))
print('{} X {:2} = {}'.format(numero, 10, numero * 10))
print('-'*11)